version: '3.9'

x-base_service: &base_service
    ports:
      - "80:80"
    volumes:
      - &v1 ./data:/data
      - &v2 ./output:/output
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]

name: webui-docker

services:
  download:
    build: ./services/download/
    profiles: ["download"]
    volumes:
      - *v1

  auto: &automatic
    <<: *base_service
    profiles: ["auto"]
    build: ./services/AUTOMATIC1111
    image: sd-auto:14
    environment:
      - CLI_ARGS=--allow-code --xformers --api
    restart: always
